[package]
name = "leaf"
version = "0.1.2"
authors = ["eycorsican <eric.y.corsican@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "leaf"
path = "src/lib.rs"

[features]
default = ["config", "endpoint", "ensemble", "ring-aead", "rustls-tls"]

ring-aead = ["ring"]
openssl-aead = ["openssl"]

rustls-tls = ["tokio-rustls", "webpki-roots"]
openssl-tls = ["openssl", "tokio-openssl", "openssl-probe"]

config = ["conf", "json"]

conf = ["regex"]
json = ["serde", "serde_derive", "serde_json"]

endpoint = ["direct", "drop", "redirect", "shadowsocks", "socks", "trojan", "vmess", "tls", "ws", "vless", "feature-h2"]
ensemble = ["failover", "random", "tryall", "chain"]

# TODO make corresponding deps optional
direct = []
drop = []
redirect = []
shadowsocks = []
socks = []
trojan = []
vmess = []
tls = []
ws = []
feature-h2 = []
vless = []

failover = []
random = []
tryall = []
chain = []

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
tungstenite = { version = "0.11", default-features = false }
tokio-tungstenite = { version = "0.11" }
hyper = { version = "0.13", default-features = false, features = [] }
h2 = { version = "0.2.6", features = ["stream"] }
futures-util = "0.3"
maxminddb = { version = "0.15.0", features = ["mmap"] }
async-socks5 = "0.3"
trust-dns-proto = "*"
protobuf = "2.17"
fern = { version = "0.5", features = ["colored"] }
socket2 = "0.3"
memmap = "0.7.0"
log = { version = "0.4", features = ["std"] }
thiserror = "1.0"
futures = "0.3"
async-trait = "0.1"
byteorder = "1.3"
md-5 = "0.9"
hkdf = "0.9"
sha-1 = "0.9"
rand = "0.7"
bytes = "0.5"
lazy_static = "1.4.0"
url = "2.1"
sha3 = "0.9"
digest = "0.9"
cfb-mode = "0.5"
aes = "0.5"
hmac = "0.9"
lz_fnv = "0.1"
uuid = "0.8"
anyhow = "1.0"
lru = "0.6"
cidr = { version = "0.1", default-features = false }
colored = "2.0"
sha2 = "0.9"
hex = "0.4"
chrono = "0.4"
httparse = "1.3"
http = "0.2"

openssl = { version = "0.10", features = ["vendored"], optional = true }
ring = { version = "0.16", optional = true }

serde_json = { version = "1.0", features = ["raw_value"], optional = true }
serde_derive = { version = "1.0", optional = true }
serde = { version = "1.0", optional = true }

regex = { version = "1.3", default-features=false, features=["std", "perf"], optional = true }

tokio-rustls = { version = "0.14", optional = true }
webpki-roots = { version = "0.20", optional = true }

openssl-probe = { version = "0.1.2", optional = true }
tokio-openssl = { version = "0.4", optional = true }

[target.'cfg(any(target_os = "ios", target_os = "macos", target_os = "linux"))'.dependencies]
tun = { git = "https://github.com/eycorsican/rust-tun.git", branch = "fix", features = ["async"] }

[build-dependencies]
cc = "1.0"
bindgen = "0.55"
protoc-rust = "2.0"
